### ISSUE TITLE
Deploying gitlab.alloy.finos.org ALSO to gitlab.<newname>.finos.org

### ISSUE THREAD

**Issue by maoo** [finos/alloy#214]
As we're getting ready to announce the open sourcing of Alloy, we're adapting the Pilot as well; one of the tasks will be to adopt a different project name, and this will impact the GitLab instance that is serving alloy.finos.org/studio

In order to prepare the pilot instance ahead of time and avoid disruptions with the current installation, we'd like to configure GitLab to serve 2 DNS hosts, the existing `gitlab.alloy.finos.org` ALSO to `gitlab.<newname>.finos.org`

Is this possible? If so, how?

**Comment by nuritzi** [comment]
Thanks @maoo! Copying Jason's response about this and adding him to this issue in case there are any follow-up questions for @gl-jayo. Please see below.

----- 

The answer is "it depends":

### The No
GitLab [does not itself support multiple DNS names](https://gitlab.com/gitlab-org/gitlab/-/issues/15430) inside the application - it only supports a single name at a time.
However, in the case of an actual _name change_ ...

### The Yes - It's Fine
If it's a simple name change - you can change the [GitLab External URL](https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-the-external-url-for-gitlab) and things generally "just work" - GitLab will internally change over ssh and https repository URLs and happily respond on the new name.

### The Maybe - What about SSL
The issue is going to be SSL - if you've [manually configured](https://docs.gitlab.com/omnibus/settings/nginx.html#manually-configuring-https) SSL - then you just need to add the old name (or new name) as a Subject Alternative Name (`SAN`) on the new certificate you obtain. GitLab will be fine responding on both names (`A records`) and give you the time you need to get everyone to change over to using the new name. I've verified this on my own manually configured installation.

If it's [Let's Encrypt](https://docs.gitlab.com/omnibus/settings/ssl.html#lets-encrypt-integration) - I'm not exactly sure what they need to do - I need to test what's possible there - this may be "no".

I'll try to spend a few minutes to test that out on Tuesday, Sept 15th.

**Comment by gl-jayo** [comment]
@maoo I spent a few minutes today with a GitLab instance that is using the default Let's Encrypt certificates - I don't think you'll be able to easily make that setup work with multiple dns records pointing at the instance.

The easiest thing to do here would be to manually configure SSL for the transition period with a certificate that has both names as a Subject Alternative Name

**Comment by maoo** [comment]
Thanks @gl-jayo for the intel ( /cc @gs-bracej ). Given what you state, I'd suggest the following way to move forward:
1. We communicate to the Alloy Pilot participants that alloy.finos.org/studio will be down for a certain amount of time
2. During the downtime, we make the changes to the GitLab domain name and update the Alloy Studio configurations
3. Restart Alloy studio and test
4. Send out announcements and notifications

@gl-jayo - anything you can provide us on step 2 , in order to prepare ahead of time , would be extremely helpful. Thank you!

**Comment by maoo** [comment]
Live upgrade is addressed by https://github.com/finos/alloy/issues/239 . Closing this issue
