### ISSUE TITLE
Review GitLab installation

### ISSUE THREAD

**Issue by maoo** [finos/alloy#237]
- GitLab Upgrade - check which versions are supported by Alloy
- [ ] Review [May blog post on GitLab Instance Security Best Practices ](https://about.gitlab.com/blog/2020/05/20/gitlab-instance-security-best-practices/)
  - [x] Review and test public/private project access
  - [x] Review and test sign-in/sign-up restrictions
  - [x] Enable `User and IP rate limits`
  - [x] Disable `allow requests to the local network from system hooks` WebHooks setting
  - [x] Checked `Enable protected paths rate limit`

**Comment by maoo** [comment]
@gs-bracej - Please check the changes I've done to the GitLab environment; none of them should impact the pilot, but please let me know if you see anything risky.

I didn't change the webhook network configuration, as I feared it could interfere with some of your logic, though it would be interesting to test it.

The backport of security fixes is something I'd like to do the day of the launch, together with GitLab, so we can install the latest patch.

**Comment by gl-jayo** [comment]
Hi @maoo - just to clarify - the words/formatting I used  [in my original comment](https://github.com/finos/alloy/issues/204#issuecomment-696367335) with regard to:

> Backport security fixes to the previous two monthly releases in addition to the current stable release - so staying within the last three months of major.minor releases will be key to keep getting security patches.

Were malformatted and confusing.  The text after the "-" should not have been blockquoted.

What I meant to convey is that [GitLab's maintenance/release policy](https://docs.gitlab.com/ee/policy/maintenance.html) is to only backport security fixes to the previous two monthly releases (other than rare exception).  And that maintaining an upgrade policy where you upgrade to a new `Major.minor` version at least once a quarter to staying on a release that will receive any future security patches.

If a security issue is discovered today that affects older GitLab releases - in addition to the current release - GitLab will just release a patch version for 13.4, 13.3, and 13.2 - after October 22nd, that will be 13.5, 13.4, and 13.3.  Backports will not be released to apply to earlier versions (with very rare/critical exceptions).

I apologize for any confusion there - I feel I might have caused some with your comment above:

> The backport of security fixes is something I'd like to do the day of the launch[...]

From a release management perspective - what to do either prior or on the day of launch is to just upgrade to the latest 13.4.x or 13.3.x version so that you have the latest security fixes, and have until either November 22nd (if upgrading to 13.3.x) or December 22nd (if upgrade to 13.4.x) to upgrade again to maintain a release that will receive security updates.

**Comment by maoo** [comment]
TY @gl-jayo !

Our current version is `12.10.12-ee` , I'm not sure we're able to update to 13.x - @gs-bracej , what are the GitLab versions that are supported by Alloy right now?

**Comment by gs-bracej** [comment]
Right now the latest version we've tested is 12.10.12 - we'll need to plan to upgrade to 13.x after the open sourcing is done.
