### ISSUE TITLE
Align all modules to new FINOS Governance

### ISSUE THREAD

**Issue by maoo** [finos/alloy#240]
Due to latest FINOS Governance updates, see https://github.com/finos/community/blob/master/governance/ , we made some updates to the `CONTRIBUTING.md` file and moved it to the repo root folder.

I applied these changes to this repo - https://github.com/finos/alloy - but also all other repositories must apply this change. @gs-bracej , can you please make sure that [https://github.com/finos/alloy/blob/master/CONTRIBUTING.md](https://github.com/finos/alloy/blob/master/CONTRIBUTING.md) is included in the root folder of each Alloy GitHub repo, and that the `.github` folder doesn't have duplicate file?

Thanks!

**Comment by gs-bracej** [comment]
This is done for the present modules, will do the same at code push for the others.

**Comment by brooklynrob** [comment]
@gs-bracej @maoo (CC @aitana16 @mcleo-d @beekemarie @nicoalba @nicoleomeara-gs) Was/is there a pull request associated with this change (it doesn't look like it)? 

Asking in part as I don't see the Contributing menu item in the alloy.finos.org any more, which I'm guessing is because it's been moved from /.github to the root (I think via https://github.com/finos/alloy/commit/0f8c5c74b26b2b93efee91f3ac1988e4538e90bf) and the build script was not updated to reflect this new location. 

A couple things:
- Can we whenever possible always make changes via PRs, not direct commits, even when it's a maintainer doing a change. This is good hygiene, improves traceability, and enforces shared patterns for contribution
- We've "lost" the content that was already there (and which we all worked on during February) and which should be the starting point for the what @aitana16 @nicoalba @nicoleomeara-gs @beekemarie and me are working on. 

I'd suggest 
- backing out this commit
- adding the new FINOS governance content to the existing file, which also had content we wanted to keep/build off of
- THEN, if it's truly necessary to move CONTRIBUTING.md to the root, doing that via a `git mv`
- Update the `https://github.com/finos/alloy/blob/master/build-site.sh` to reflect the new location
- THEN, submit a PR that contains a these changes.

There is content and copy in (what was) the existing CONTRIBUTING.md file we can still use -- there's no need to be writing this from scratch. Moreover, we've lost the contributing item from the existing documentation site and while it's a bit outdated, it was there for a reason. PLEASE do not build a new CONTRIBUTING.md from scratch -- build off the copy we already wrote (and incorporate the new governance stuff into that). As context, here's what the copy looked like previously (as of late February):
- https://brooklynrob.github.io/alloy/docs/contribute
- https://github.com/brooklynrob/alloy/blob/master/.github/CONTRIBUTING.md

**Comment by maoo** [comment]
> Asking in part as I don't see the Contributing menu item in the alloy.finos.org any more, which I'm guessing is because it's been moved from /.github to the root (I think via 0f8c5c7) and the build script was not updated to reflect this new location.

@brooklynrob - well spotted, I provided a PR to fix this, see https://github.com/finos/alloy/pull/242

Re. contents, I'll let @gs-bracej follow up based on Rob's suggestions above.

**Comment by maoo** [comment]
Submitted https://github.com/finos/legend-shared/pull/52 . When merged, we'll apply to all other repos.

**Comment by maoo** [comment]
All done!

All repositories include a CONTRIBUTING.md in the root folder, which describes FINOS project governance; README includes roadmap and contributing links to the main repo.
